[package]
name = "parity-secretstore-blockchain-service"
version = "1.0.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
ethereum-types = "0.8"
futures = "0.3"
log = "0.4"
parity-secretstore-primitives = { git = "https://github.com/svyatonik/secretstore-primitives.git" }
parking_lot = "0.10"